working_dir: "/home/steffen/Youtube"
yt_dlp:
  archive_path: archive.txt
  playlist_id: PLN9HStrYxE0B2nVpDJkOMyXUa7Arf2kon
  target_dir: "untagged"
adb_sync:
  executable: "adb-sync"
  remote_path: "storage/emulated/0/Music"
  include_folders: ["tagged", "untagged"]

